<?php

declare(strict_types=1);

/*
 * PayPalRESTAPIsLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

namespace PayPalRESTAPIsLib\Models\Builders;

use Core\Utils\CoreHelper;
use PayPalRESTAPIsLib\Models\BLIKOneClickPaymentObject;

/**
 * Builder for model BLIKOneClickPaymentObject
 *
 * @see BLIKOneClickPaymentObject
 */
class BLIKOneClickPaymentObjectBuilder
{
    /**
     * @var BLIKOneClickPaymentObject
     */
    private $instance;

    private function __construct(BLIKOneClickPaymentObject $instance)
    {
        $this->instance = $instance;
    }

    /**
     * Initializes a new BLIK One Click Payment Object Builder object.
     */
    public static function init(): self
    {
        return new self(new BLIKOneClickPaymentObject());
    }

    /**
     * Sets consumer reference field.
     *
     * @param string|null $value
     */
    public function consumerReference(?string $value): self
    {
        $this->instance->setConsumerReference($value);
        return $this;
    }

    /**
     * Initializes a new BLIK One Click Payment Object object.
     */
    public function build(): BLIKOneClickPaymentObject
    {
        return CoreHelper::clone($this->instance);
    }
}
