<?php

declare(strict_types=1);

/*
 * PayPalRESTAPIsLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

namespace PayPalRESTAPIsLib\Models\Builders;

use Core\Utils\CoreHelper;
use PayPalRESTAPIsLib\Models\CustomerRequest;
use PayPalRESTAPIsLib\Models\PaymentTokenRequest;
use PayPalRESTAPIsLib\Models\PaymentTokenRequestPaymentSource;

/**
 * Builder for model PaymentTokenRequest
 *
 * @see PaymentTokenRequest
 */
class PaymentTokenRequestBuilder
{
    /**
     * @var PaymentTokenRequest
     */
    private $instance;

    private function __construct(PaymentTokenRequest $instance)
    {
        $this->instance = $instance;
    }

    /**
     * Initializes a new Payment Token Request Builder object.
     *
     * @param PaymentTokenRequestPaymentSource $paymentSource
     */
    public static function init(PaymentTokenRequestPaymentSource $paymentSource): self
    {
        return new self(new PaymentTokenRequest($paymentSource));
    }

    /**
     * Sets customer field.
     *
     * @param CustomerRequest|null $value
     */
    public function customer(?CustomerRequest $value): self
    {
        $this->instance->setCustomer($value);
        return $this;
    }

    /**
     * Initializes a new Payment Token Request object.
     */
    public function build(): PaymentTokenRequest
    {
        return CoreHelper::clone($this->instance);
    }
}
