<?php

declare(strict_types=1);

/*
 * PayPalRESTAPIsLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

namespace PayPalRESTAPIsLib\Models\Builders;

use Core\Utils\CoreHelper;
use PayPalRESTAPIsLib\Models\LinkDescription;
use PayPalRESTAPIsLib\Models\PayPalWalletCustomer;
use PayPalRESTAPIsLib\Models\PayPalWalletVaultResponse;

/**
 * Builder for model PayPalWalletVaultResponse
 *
 * @see PayPalWalletVaultResponse
 */
class PayPalWalletVaultResponseBuilder
{
    /**
     * @var PayPalWalletVaultResponse
     */
    private $instance;

    private function __construct(PayPalWalletVaultResponse $instance)
    {
        $this->instance = $instance;
    }

    /**
     * Initializes a new Pay Pal Wallet Vault Response Builder object.
     */
    public static function init(): self
    {
        return new self(new PayPalWalletVaultResponse());
    }

    /**
     * Sets id field.
     *
     * @param string|null $value
     */
    public function id(?string $value): self
    {
        $this->instance->setId($value);
        return $this;
    }

    /**
     * Sets status field.
     *
     * @param string|null $value
     */
    public function status(?string $value): self
    {
        $this->instance->setStatus($value);
        return $this;
    }

    /**
     * Sets links field.
     *
     * @param LinkDescription[]|null $value
     */
    public function links(?array $value): self
    {
        $this->instance->setLinks($value);
        return $this;
    }

    /**
     * Sets customer field.
     *
     * @param PayPalWalletCustomer|null $value
     */
    public function customer(?PayPalWalletCustomer $value): self
    {
        $this->instance->setCustomer($value);
        return $this;
    }

    /**
     * Initializes a new Pay Pal Wallet Vault Response object.
     */
    public function build(): PayPalWalletVaultResponse
    {
        return CoreHelper::clone($this->instance);
    }
}
