<?php

declare(strict_types=1);

/*
 * PayPalRESTAPIsLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

namespace PayPalRESTAPIsLib\Models\Builders;

use Core\Utils\CoreHelper;
use PayPalRESTAPIsLib\Models\Address;
use PayPalRESTAPIsLib\Models\Name;
use PayPalRESTAPIsLib\Models\PayPalWalletAttributesResponse;
use PayPalRESTAPIsLib\Models\PayPalWalletResponse;
use PayPalRESTAPIsLib\Models\PhoneNumber;
use PayPalRESTAPIsLib\Models\TaxInfo;

/**
 * Builder for model PayPalWalletResponse
 *
 * @see PayPalWalletResponse
 */
class PayPalWalletResponseBuilder
{
    /**
     * @var PayPalWalletResponse
     */
    private $instance;

    private function __construct(PayPalWalletResponse $instance)
    {
        $this->instance = $instance;
    }

    /**
     * Initializes a new Pay Pal Wallet Response Builder object.
     */
    public static function init(): self
    {
        return new self(new PayPalWalletResponse());
    }

    /**
     * Sets email address field.
     *
     * @param string|null $value
     */
    public function emailAddress(?string $value): self
    {
        $this->instance->setEmailAddress($value);
        return $this;
    }

    /**
     * Sets account id field.
     *
     * @param string|null $value
     */
    public function accountId(?string $value): self
    {
        $this->instance->setAccountId($value);
        return $this;
    }

    /**
     * Sets account status field.
     *
     * @param string|null $value
     */
    public function accountStatus(?string $value): self
    {
        $this->instance->setAccountStatus($value);
        return $this;
    }

    /**
     * Sets name field.
     *
     * @param Name|null $value
     */
    public function name(?Name $value): self
    {
        $this->instance->setName($value);
        return $this;
    }

    /**
     * Sets phone type field.
     *
     * @param string|null $value
     */
    public function phoneType(?string $value): self
    {
        $this->instance->setPhoneType($value);
        return $this;
    }

    /**
     * Sets phone number field.
     *
     * @param PhoneNumber|null $value
     */
    public function phoneNumber(?PhoneNumber $value): self
    {
        $this->instance->setPhoneNumber($value);
        return $this;
    }

    /**
     * Sets birth date field.
     *
     * @param string|null $value
     */
    public function birthDate(?string $value): self
    {
        $this->instance->setBirthDate($value);
        return $this;
    }

    /**
     * Sets tax info field.
     *
     * @param TaxInfo|null $value
     */
    public function taxInfo(?TaxInfo $value): self
    {
        $this->instance->setTaxInfo($value);
        return $this;
    }

    /**
     * Sets address field.
     *
     * @param Address|null $value
     */
    public function address(?Address $value): self
    {
        $this->instance->setAddress($value);
        return $this;
    }

    /**
     * Sets attributes field.
     *
     * @param PayPalWalletAttributesResponse|null $value
     */
    public function attributes(?PayPalWalletAttributesResponse $value): self
    {
        $this->instance->setAttributes($value);
        return $this;
    }

    /**
     * Initializes a new Pay Pal Wallet Response object.
     */
    public function build(): PayPalWalletResponse
    {
        return CoreHelper::clone($this->instance);
    }
}
