<?php

declare(strict_types=1);

/*
 * PayPalRESTAPIsLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

namespace PayPalRESTAPIsLib\Models\Builders;

use Core\Utils\CoreHelper;
use PayPalRESTAPIsLib\Models\PayPalWalletAttributes;
use PayPalRESTAPIsLib\Models\PayPalWalletCustomerRequest;
use PayPalRESTAPIsLib\Models\PayPalWalletVaultInstruction;

/**
 * Builder for model PayPalWalletAttributes
 *
 * @see PayPalWalletAttributes
 */
class PayPalWalletAttributesBuilder
{
    /**
     * @var PayPalWalletAttributes
     */
    private $instance;

    private function __construct(PayPalWalletAttributes $instance)
    {
        $this->instance = $instance;
    }

    /**
     * Initializes a new Pay Pal Wallet Attributes Builder object.
     */
    public static function init(): self
    {
        return new self(new PayPalWalletAttributes());
    }

    /**
     * Sets customer field.
     *
     * @param PayPalWalletCustomerRequest|null $value
     */
    public function customer(?PayPalWalletCustomerRequest $value): self
    {
        $this->instance->setCustomer($value);
        return $this;
    }

    /**
     * Sets vault field.
     *
     * @param PayPalWalletVaultInstruction|null $value
     */
    public function vault(?PayPalWalletVaultInstruction $value): self
    {
        $this->instance->setVault($value);
        return $this;
    }

    /**
     * Initializes a new Pay Pal Wallet Attributes object.
     */
    public function build(): PayPalWalletAttributes
    {
        return CoreHelper::clone($this->instance);
    }
}
