<?php

declare(strict_types=1);

/*
 * PayPalRESTAPIsLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

namespace PayPalRESTAPIsLib\Models\Builders;

use Core\Utils\CoreHelper;
use PayPalRESTAPIsLib\Models\VaultedDigitalWalletShippingDetails;
use PayPalRESTAPIsLib\Models\VaultExperienceContext;
use PayPalRESTAPIsLib\Models\VaultPayPalWalletRequest;

/**
 * Builder for model VaultPayPalWalletRequest
 *
 * @see VaultPayPalWalletRequest
 */
class VaultPayPalWalletRequestBuilder
{
    /**
     * @var VaultPayPalWalletRequest
     */
    private $instance;

    private function __construct(VaultPayPalWalletRequest $instance)
    {
        $this->instance = $instance;
    }

    /**
     * Initializes a new Vault Pay Pal Wallet Request Builder object.
     */
    public static function init(): self
    {
        return new self(new VaultPayPalWalletRequest());
    }

    /**
     * Sets description field.
     *
     * @param string|null $value
     */
    public function description(?string $value): self
    {
        $this->instance->setDescription($value);
        return $this;
    }

    /**
     * Sets shipping field.
     *
     * @param VaultedDigitalWalletShippingDetails|null $value
     */
    public function shipping(?VaultedDigitalWalletShippingDetails $value): self
    {
        $this->instance->setShipping($value);
        return $this;
    }

    /**
     * Sets permit multiple payment tokens field.
     *
     * @param bool|null $value
     */
    public function permitMultiplePaymentTokens(?bool $value): self
    {
        $this->instance->setPermitMultiplePaymentTokens($value);
        return $this;
    }

    /**
     * Sets usage type field.
     *
     * @param string|null $value
     */
    public function usageType(?string $value): self
    {
        $this->instance->setUsageType($value);
        return $this;
    }

    /**
     * Sets customer type field.
     *
     * @param string|null $value
     */
    public function customerType(?string $value): self
    {
        $this->instance->setCustomerType($value);
        return $this;
    }

    /**
     * Sets experience context field.
     *
     * @param VaultExperienceContext|null $value
     */
    public function experienceContext(?VaultExperienceContext $value): self
    {
        $this->instance->setExperienceContext($value);
        return $this;
    }

    /**
     * Initializes a new Vault Pay Pal Wallet Request object.
     */
    public function build(): VaultPayPalWalletRequest
    {
        return CoreHelper::clone($this->instance);
    }
}
