<?php

declare(strict_types=1);

/*
 * PayPalRESTAPIsLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

namespace PayPalRESTAPIsLib\Models;

/**
 * Indicates the type of payment data passed, in case of Non China the payment data is 3DSECURE and for
 * China it is EMV.
 */
class ApplePayPaymentDataType
{
    public const ENUM_3DSECURE = '3DSECURE';

    public const EMV = 'EMV';
}
