<?php

declare(strict_types=1);

/*
 * PayPalRESTAPIsLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

namespace PayPalRESTAPIsLib\Models;

/**
 * The address verification code for Visa, Discover, Mastercard, or American Express transactions.
 */
class AVSCode
{
    public const A = 'A';

    public const B = 'B';

    public const C = 'C';

    public const D = 'D';

    public const E = 'E';

    public const F = 'F';

    public const G = 'G';

    public const I = 'I';

    public const M = 'M';

    public const N = 'N';

    public const P = 'P';

    public const R = 'R';

    public const S = 'S';

    public const U = 'U';

    public const W = 'W';

    public const X = 'X';

    public const Y = 'Y';

    public const Z = 'Z';

    public const NULL = 'Null';

    public const ENUM_0 = '0';

    public const ENUM_1 = '1';

    public const ENUM_2 = '2';

    public const ENUM_3 = '3';

    public const ENUM_4 = '4';
}
