<?php

declare(strict_types=1);

/*
 * PayPalRESTAPIsLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

namespace PayPalRESTAPIsLib\Models;

/**
 * The reason why the captured payment status is `PENDING` or `DENIED`.
 */
class CaptureIncompleteReason
{
    public const BUYER_COMPLAINT = 'BUYER_COMPLAINT';

    public const CHARGEBACK = 'CHARGEBACK';

    public const ECHECK = 'ECHECK';

    public const INTERNATIONAL_WITHDRAWAL = 'INTERNATIONAL_WITHDRAWAL';

    public const OTHER = 'OTHER';

    public const PENDING_REVIEW = 'PENDING_REVIEW';

    public const RECEIVING_PREFERENCE_MANDATES_MANUAL_ACTION = 'RECEIVING_PREFERENCE_MANDATES_MANUAL_ACTION';

    public const REFUNDED = 'REFUNDED';

    public const TRANSACTION_APPROVED_AWAITING_FUNDING = 'TRANSACTION_APPROVED_AWAITING_FUNDING';

    public const UNILATERAL = 'UNILATERAL';

    public const VERIFICATION_REQUIRED = 'VERIFICATION_REQUIRED';

    public const DECLINED_BY_RISK_FRAUD_FILTERS = 'DECLINED_BY_RISK_FRAUD_FILTERS';
}
