<?php

declare(strict_types=1);

/*
 * PayPalRESTAPIsLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

namespace PayPalRESTAPIsLib\Models;

/**
 * Type of card. i.e Credit, Debit and so on.
 */
class CardType
{
    public const CREDIT = 'CREDIT';

    public const DEBIT = 'DEBIT';

    public const PREPAID = 'PREPAID';

    public const STORE = 'STORE';

    public const UNKNOWN = 'UNKNOWN';
}
