<?php

declare(strict_types=1);

/*
 * PayPalRESTAPIsLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

namespace PayPalRESTAPIsLib\Models;

/**
 * The card network or brand. Applies to credit, debit, gift, and payment cards.
 */
class CardBrand
{
    public const VISA = 'VISA';

    public const MASTERCARD = 'MASTERCARD';

    public const DISCOVER = 'DISCOVER';

    public const AMEX = 'AMEX';

    public const SOLO = 'SOLO';

    public const JCB = 'JCB';

    public const STAR = 'STAR';

    public const DELTA = 'DELTA';

    public const SWITCH_ = 'SWITCH';

    public const MAESTRO = 'MAESTRO';

    public const CB_NATIONALE = 'CB_NATIONALE';

    public const CONFIGOGA = 'CONFIGOGA';

    public const CONFIDIS = 'CONFIDIS';

    public const ELECTRON = 'ELECTRON';

    public const CETELEM = 'CETELEM';

    public const CHINA_UNION_PAY = 'CHINA_UNION_PAY';

    public const DINERS = 'DINERS';

    public const ELO = 'ELO';

    public const HIPER = 'HIPER';

    public const HIPERCARD = 'HIPERCARD';

    public const RUPAY = 'RUPAY';

    public const GE = 'GE';

    public const SYNCHRONY = 'SYNCHRONY';

    public const UNKNOWN = 'UNKNOWN';
}
