<?php

declare(strict_types=1);

/*
 * PayPalRESTAPIsLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

namespace PayPalRESTAPIsLib\Models;

/**
 * The card verification value code for for Visa, Discover, Mastercard, or American Express.
 */
class CVVCode
{
    public const E = 'E';

    public const I = 'I';

    public const M = 'M';

    public const N = 'N';

    public const P = 'P';

    public const S = 'S';

    public const U = 'U';

    public const X = 'X';

    public const ENUM_ALL_OTHERS = 'All others';

    public const ENUM_0 = '0';

    public const ENUM_1 = '1';

    public const ENUM_2 = '2';

    public const ENUM_3 = '3';

    public const ENUM_4 = '4';
}
