<?php

declare(strict_types=1);

/*
 * PayPalRESTAPIsLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

namespace PayPalRESTAPIsLib\Models;

/**
 * The funds that are held on behalf of the merchant.
 */
class DisbursementMode
{
    public const INSTANT = 'INSTANT';

    public const DELAYED = 'DELAYED';
}
