<?php

declare(strict_types=1);

/*
 * PayPalRESTAPIsLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

namespace PayPalRESTAPIsLib\Models;

/**
 * The type of the payment credential. Currently, only CARD is supported.
 */
class GooglePayPaymentMethod
{
    public const CARD = 'CARD';
}
