<?php

declare(strict_types=1);

/*
 * PayPalRESTAPIsLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

namespace PayPalRESTAPIsLib\Models;

/**
 * Authentication Method which is used for the card transaction.
 */
class GooglePayAuthenticationMethod
{
    public const PAN_ONLY = 'PAN_ONLY';

    public const CRYPTOGRAM_3DS = 'CRYPTOGRAM_3DS';
}
