<?php

declare(strict_types=1);

/*
 * PayPalRESTAPIsLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

namespace PayPalRESTAPIsLib\Models;

/**
 * The item category type.
 */
class ItemCategory
{
    public const DIGITAL_GOODS = 'DIGITAL_GOODS';

    public const PHYSICAL_GOODS = 'PHYSICAL_GOODS';

    public const DONATION = 'DONATION';
}
