<?php

declare(strict_types=1);

/*
 * PayPalRESTAPIsLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

namespace PayPalRESTAPIsLib\Models;

/**
 * Liability shift indicator. The outcome of the issuer's authentication.
 */
class LiabilityShiftIndicator
{
    public const NO = 'NO';

    public const POSSIBLE = 'POSSIBLE';

    public const UNKNOWN = 'UNKNOWN';
}
