<?php

declare(strict_types=1);

/*
 * PayPalRESTAPIsLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

namespace PayPalRESTAPIsLib\Models;

/**
 * The status of the item shipment.
 */
class OrderTrackerStatus
{
    public const CANCELLED = 'CANCELLED';

    public const SHIPPED = 'SHIPPED';
}
