<?php

declare(strict_types=1);

/*
 * PayPalRESTAPIsLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

namespace PayPalRESTAPIsLib\Models;

/**
 * The order status.
 */
class OrderStatus
{
    public const CREATED = 'CREATED';

    public const SAVED = 'SAVED';

    public const APPROVED = 'APPROVED';

    public const VOIDED = 'VOIDED';

    public const COMPLETED = 'COMPLETED';

    public const PAYER_ACTION_REQUIRED = 'PAYER_ACTION_REQUIRED';
}
