<?php

declare(strict_types=1);

/*
 * PayPalRESTAPIsLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

namespace PayPalRESTAPIsLib\Models;

/**
 * DEPRECATED. Configures a <strong>Continue</strong> or <strong>Pay Now</strong> checkout flow.  The
 * fields in `application_context` are now available in the `experience_context` object under the
 * `payment_source` which supports them (eg. `payment_source.paypal.experience_context.user_action`).
 * Please specify this field in the `experience_context` object instead of the `application_context`
 * object.
 */
class OrderApplicationContextUserAction
{
    public const CONTINUE_ = 'CONTINUE';

    public const PAY_NOW = 'PAY_NOW';
}
