<?php

declare(strict_types=1);

/*
 * PayPalRESTAPIsLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

namespace PayPalRESTAPIsLib\Models;

/**
 * Transactions status result identifier. The outcome of the issuer's authentication.
 */
class PAResStatus
{
    public const Y = 'Y';

    public const N = 'N';

    public const U = 'U';

    public const A = 'A';

    public const C = 'C';

    public const R = 'R';

    public const D = 'D';

    public const I = 'I';
}
