<?php

declare(strict_types=1);

/*
 * PayPalRESTAPIsLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

namespace PayPalRESTAPIsLib\Models;

/**
 * The type of landing page to show on the PayPal site for customer checkout.
 */
class PayPalExperienceLandingPage
{
    public const LOGIN = 'LOGIN';

    public const GUEST_CHECKOUT = 'GUEST_CHECKOUT';

    public const NO_PREFERENCE = 'NO_PREFERENCE';
}
