<?php

declare(strict_types=1);

/*
 * PayPalRESTAPIsLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

namespace PayPalRESTAPIsLib\Models;

/**
 * The vault status.
 */
class PayPalWalletVaultStatus
{
    public const VAULTED = 'VAULTED';

    public const CREATED = 'CREATED';

    public const APPROVED = 'APPROVED';
}
