<?php

declare(strict_types=1);

/*
 * PayPalRESTAPIsLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

namespace PayPalRESTAPIsLib\Models;

/**
 * The customer type associated with the PayPal payment token. This is to indicate whether the customer
 * acting on the merchant / platform is either a business or a consumer.
 */
class PayPalPaymentTokenCustomerType
{
    public const CONSUMER = 'CONSUMER';

    public const BUSINESS = 'BUSINESS';
}
