<?php

declare(strict_types=1);

/*
 * PayPalRESTAPIsLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

namespace PayPalRESTAPIsLib\Models;

/**
 * The status of the refund.
 */
class RefundStatus
{
    public const CANCELLED = 'CANCELLED';

    public const FAILED = 'FAILED';

    public const PENDING = 'PENDING';

    public const COMPLETED = 'COMPLETED';
}
