<?php

declare(strict_types=1);

/*
 * PayPalRESTAPIsLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

namespace PayPalRESTAPIsLib\Models;

/**
 * The reason why the refund has the `PENDING` or `FAILED` status.
 */
class RefundIncompleteReason
{
    public const ECHECK = 'ECHECK';
}
