<?php

declare(strict_types=1);

/*
 * PayPalRESTAPIsLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

namespace PayPalRESTAPIsLib\Models;

/**
 * Indicates whether the transaction is eligible for seller protection. For information, see [PayPal
 * Seller Protection for Merchants](https://www.paypal.com/us/webapps/mpp/security/seller-protection).
 */
class SellerProtectionStatus
{
    public const ELIGIBLE = 'ELIGIBLE';

    public const PARTIALLY_ELIGIBLE = 'PARTIALLY_ELIGIBLE';

    public const NOT_ELIGIBLE = 'NOT_ELIGIBLE';
}
