<?php

declare(strict_types=1);

/*
 * PayPalRESTAPIsLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

namespace PayPalRESTAPIsLib\Models;

/**
 * A classification for the method of purchase fulfillment.
 */
class ShippingType
{
    public const SHIPPING = 'SHIPPING';

    public const PICKUP = 'PICKUP';

    public const PICKUP_IN_STORE = 'PICKUP_IN_STORE';

    public const PICKUP_FROM_PERSON = 'PICKUP_FROM_PERSON';
}
