<?php

declare(strict_types=1);

/*
 * PayPalRESTAPIsLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

namespace PayPalRESTAPIsLib\Models;

/**
 * The location from which the shipping address is derived.
 */
class ShippingPreference
{
    public const GET_FROM_FILE = 'GET_FROM_FILE';

    public const NO_SHIPPING = 'NO_SHIPPING';

    public const SET_PROVIDED_ADDRESS = 'SET_PROVIDED_ADDRESS';
}
