<?php

declare(strict_types=1);

/*
 * PayPalRESTAPIsLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

namespace PayPalRESTAPIsLib\Models;

/**
 * Defines how and when the payment source gets vaulted.
 */
class StoreInVaultInstruction
{
    public const ON_SUCCESS = 'ON_SUCCESS';
}
