<?php

declare(strict_types=1);

/*
 * PayPalRESTAPIsLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

namespace PayPalRESTAPIsLib\Models;

/**
 * The tokenization method that generated the ID.
 */
class TokenType
{
    public const BILLING_AGREEMENT = 'BILLING_AGREEMENT';
}
