<?php

declare(strict_types=1);

/*
 * PayPalRESTAPIsLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

namespace PayPalRESTAPIsLib\Models;

/**
 * The Universal Product Code type.
 */
class UPCType
{
    public const UPCA = 'UPC-A';

    public const UPCB = 'UPC-B';

    public const UPCC = 'UPC-C';

    public const UPCD = 'UPC-D';

    public const UPCE = 'UPC-E';

    public const UPC2 = 'UPC-2';

    public const UPC5 = 'UPC-5';
}
