<?php

declare(strict_types=1);

/*
 * PayPalRESTAPIsLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

namespace PayPalRESTAPIsLib\Models;

/**
 * The usage type associated with the Venmo payment token.
 */
class VenmoPaymentTokenUsageType
{
    public const MERCHANT = 'MERCHANT';

    public const PLATFORM = 'PLATFORM';
}
